version: 2
jobs:
  lint:
    docker:
      - image: cimg/go:1.17
    resource_class: small
    working_directory: ~/env
    steps:
      - checkout
      - run: make install
      - run: make lint


  tests:
    docker:
      - image: cimg/go:1.17
    resource_class: small
    working_directory: ~/env
    steps:
      - checkout
      - run: make install
      - run: make cover
      - run: make deploy-cover


  bench:
    docker:
      - image: cimg/go:1.17
    resource_class: small
    working_directory: ~/env
    steps:
      - checkout
      - run: make install
      - run: make bench

  # release:
  #   docker:
  #     - image: cimg/go:1.17
  #   working_directory: ~/env
  #   steps:
  #     - checkout
  #     - run: make install
  #     - run: make release

workflows:
  version: 2
  build:
    jobs:
      - lint
      - tests
      - bench
      # - release:
      #     requires:
      #       - lint
      #       - tests
      #       - bench
      #     filters:
      #       branches:
      #         only: master